----------------Sales exploration
-----Total sales-
SELECT 
    ROUND(SUM(CASE WHEN COALESCE(s.salesdollars,0) < 0 THEN 0
            ELSE COALESCE(s.salesdollars,0)
        END),2) AS total_sales
FROM sales s;

---Average sales 
SELECT 
    ROUND(AVG(CASE WHEN COALESCE(s.salesdollars,0) < 0 THEN 0
            ELSE COALESCE(s.salesdollars,0)
        END),2) AS avg_sales
FROM sales s;


-----Sales by brand
SELECT 
    e.brand,
    ROUND(SUM(
        CASE WHEN COALESCE(s.salesdollars,0) < 0 THEN 0
            ELSE COALESCE(s.salesdollars,0)
        END),2) AS total_sales
FROM sales s
JOIN end_inventory e
    ON s.inventoryid = e.inventoryid
GROUP BY e.brand
ORDER BY total_sales DESC;


----Sales by description
SELECT 
    e.description,
    ROUND(SUM(CASE 
            WHEN COALESCE(s.salesdollars,0) < 0 THEN 0
            ELSE COALESCE(s.salesdollars,0)
        END),2) AS total_sales
FROM sales s
JOIN end_inventory e
    ON s.inventoryid = e.inventoryid
GROUP BY e.description
ORDER BY total_sales DESC;


------Sales by city
SELECT 
    e.city,
    ROUND(SUM(CASE WHEN COALESCE(s.salesdollars,0) < 0 THEN 0
            ELSE COALESCE(s.salesdollars,0)
        END),2) AS total_sales
FROM sales s
JOIN end_inventory e
    ON s.inventoryid = e.inventoryid
GROUP BY e.city
ORDER BY total_sales DESC;


------Sales by store
SELECT 
    e.store,
    ROUND(SUM(CASE WHEN COALESCE(s.salesdollars,0) < 0 THEN 0
            ELSE COALESCE(s.salesdollars,0)
        END),2) AS total_sales
FROM sales s
JOIN end_inventory e
    ON s.inventoryid = e.inventoryid
GROUP BY e.store
ORDER BY total_sales DESC;


-----Sales by Month
SELECT 
    FORMAT(s.salesdate,'yyyy-MMM') AS sales_month,
    ROUND(SUM(CASE WHEN COALESCE(s.salesdollars,0) < 0 THEN 0
            ELSE COALESCE(s.salesdollars,0)
        END),2) AS total_sales
FROM sales s
GROUP BY FORMAT(s.salesdate,'yyyy-MMM')
ORDER BY sales_month;


-------------------------------------------------
----Profit explorations and measure
---Profit generated by cities 
SELECT 
    e.city,
    ROUND(SUM(CASE WHEN COALESCE(s.salesprice, 0) - COALESCE(pp.purchaseprice, 0) < 0 THEN 0
                ELSE COALESCE(s.salesprice, 0) - COALESCE(pp.purchaseprice, 0)
            END), 2 ) AS total_profit
FROM sales s
JOIN end_inventory e
    ON s.InventoryId = e.InventoryId
JOIN purchase_prices pp
    ON s.brand = pp.brand
   AND s.description = pp.description
   AND s.size = pp.size
GROUP BY e.city
ORDER BY total_profit DESC;


------Profit by description
SELECT 
    s.description,
    ROUND(SUM( CASE WHEN COALESCE(s.salesprice, 0) - COALESCE(pp.purchaseprice, 0) < 0 THEN 0
                ELSE COALESCE(s.salesprice, 0) - COALESCE(pp.purchaseprice, 0)
            END ),  2) AS total_profit
FROM sales s
JOIN purchase_prices pp
    ON s.brand = pp.brand
   AND s.description = pp.description
   AND s.size = pp.size
GROUP BY s.description
ORDER BY total_profit DESC;


----Profit by brand
SELECT 
    s.brand,
    ROUND( SUM( CASE  WHEN COALESCE(s.salesprice, 0) - COALESCE(pp.purchaseprice, 0) < 0 THEN 0
                ELSE COALESCE(s.salesprice, 0) - COALESCE(pp.purchaseprice, 0)
                END ), 2) AS total_profit
FROM sales s
JOIN purchase_prices pp
    ON s.brand = pp.brand
   AND s.description = pp.description
   AND s.size = pp.size
GROUP BY s.brand
ORDER BY total_profit DESC;


--------
SELECT 
    CASE WHEN s.salesprice < 41 THEN 'Low'
        WHEN s.salesprice BETWEEN 41 AND 100 THEN 'Medium'
        WHEN s.salesprice BETWEEN 101 AND 200 THEN 'High'
        ELSE 'Ultra-High'
    END AS price_class,
    ROUND( SUM(CASE WHEN COALESCE(s.salesprice, 0) - COALESCE(pp.purchaseprice, 0) < 0 THEN 0
                ELSE COALESCE(s.salesprice, 0) - COALESCE(pp.purchaseprice, 0)
            END), 2) AS total_profit
FROM sales s
JOIN purchase_prices pp
    ON s.brand = pp.brand
   AND s.description = pp.description
   AND s.size = pp.size
GROUP BY 
    CASE 
        WHEN s.salesprice < 41 THEN 'Low'
        WHEN s.salesprice BETWEEN 41 AND 100 THEN 'Medium'
        WHEN s.salesprice BETWEEN 101 AND 200 THEN 'High'
        ELSE 'Ultra-High'
    END
ORDER BY total_profit DESC;


---------
-----Profit by Month
SELECT 
    FORMAT(s.salesdate, 'yyyy-MMM') AS profit_month,
    ROUND(SUM( CASE WHEN COALESCE(s.salesdollars,0) - COALESCE(pp.purchaseprice,0) < 0 THEN 0
            ELSE COALESCE(s.salesdollars,0) - COALESCE(pp.purchaseprice,0)
        END),2) AS total_profit
FROM sales s
JOIN purchase_prices pp
    ON s.brand = pp.brand   -- simple join as you requested
GROUP BY FORMAT(s.salesdate, 'yyyy-MMM')
ORDER BY profit_month;


-----Profit by month for presentation and $
SELECT 
    FORMAT(s.salesdate, 'yyyy-MMM') AS profit_month,
    '$' + FORMAT(SUM( CASE WHEN COALESCE(s.salesdollars,0) - COALESCE(pp.purchaseprice,0) < 0 THEN 0
            ELSE COALESCE(s.salesdollars,0) - COALESCE(pp.purchaseprice,0)
        END), 'N2') AS total_profit
FROM sales s
JOIN purchase_prices pp
    ON s.brand = pp.brand
GROUP BY FORMAT(s.salesdate, 'yyyy-MMM')
ORDER BY profit_month;


----------------------------------
------Quantity exploration and magnitude
---Total Quantity
SELECT 
    SUM(CASE WHEN COALESCE(quantity, 0) < 0 THEN 0
            ELSE COALESCE(quantity, 0)
        END) AS total_quantity
FROM purchases;



-----Quantity by store
SELECT 
    store,
    SUM(
        CASE 
            WHEN COALESCE(Quantity, 0) <= 0 THEN 0
            ELSE COALESCE(Quantity, 0)
        END
    ) AS total_quantity
FROM purchases 
GROUP BY store
ORDER BY total_quantity DESC;

------
----QUANTITY BY CITY
SELECT 
    e.city,
    SUM(CASE  WHEN COALESCE(p.Quantity, 0) <= 0 THEN 0
            ELSE COALESCE(p.Quantity, 0)
        END) AS total_quantity
FROM purchases p
JOIN end_inventory e
    ON p.InventoryId = e.InventoryId
GROUP BY e.city
ORDER BY total_quantity DESC;



----QUANTITY BY BRAND
SELECT 
    Brand,
    SUM(
        CASE WHEN COALESCE(Quantity, 0) <= 0 THEN 0
            ELSE COALESCE(Quantity, 0)
        END) AS total_quantity
FROM purchases 
GROUP BY Brand
ORDER BY total_quantity DESC;


-------QUANTITY BY DESCRIPTION
SELECT 
    Description,
    SUM(CASE WHEN COALESCE(Quantity, 0) <= 0 THEN 0
            ELSE COALESCE(Quantity, 0)
        END) AS total_quantity
FROM purchases 
GROUP BY Description
ORDER BY total_quantity DESC;


-------Quantity by price class
SELECT 
    CASE WHEN p.PurchasePrice < 22 THEN 'Low'
        WHEN p.PurchasePrice BETWEEN 22 AND 50 THEN 'Average'
        WHEN p.PurchasePrice BETWEEN 51 AND 500 THEN 'High'
        ELSE 'Ultra-High'
    END AS price_class,
    SUM(CASE WHEN COALESCE(p.Quantity, 0) <= 0 THEN 0
            ELSE COALESCE(p.Quantity, 0)
        END) AS total_quantity
FROM purchases p
GROUP BY 
    CASE 
        WHEN p.PurchasePrice < 22 THEN 'Low'
        WHEN p.PurchasePrice BETWEEN 22 AND 50 THEN 'Average'
        WHEN p.PurchasePrice BETWEEN 51 AND 500 THEN 'High'
        ELSE 'Ultra-High'
    END
ORDER BY total_quantity DESC;


-----Quantity by Month
SELECT 
    FORMAT(PODate, 'yyyy-MMM') AS purchase_month,
    SUM(CASE WHEN COALESCE(quantity, 0) < 0 THEN 0
            ELSE COALESCE(quantity, 0)
        END ) AS total_quantity
FROM purchases
GROUP BY FORMAT(PODate, 'yyyy-MMM')
ORDER BY purchase_month;


